#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# IT Ticketing System — Codespaces startup script  (Phase 8)
# Usage: cd /path/to/it-ticketing-phase8 && bash start.sh
# ─────────────────────────────────────────────────────────────────────────────
set -e
ROOT="$(cd "$(dirname "$0")" && pwd)"
BACKEND="$ROOT/backend"
FRONTEND="$ROOT/frontend"

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║   IT Ticketing System — Starting up      ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── 1. Kill anything on ports 3000 / 5000 ────────────────────────────────────
echo "[1/6] Clearing ports 3000 and 5000…"
fuser -k 3000/tcp 2>/dev/null || true
fuser -k 5000/tcp 2>/dev/null || true
sleep 1

# ── 2. Detect Codespaces or local ────────────────────────────────────────────
echo "[2/6] Detecting environment…"
if [ -n "$CODESPACE_NAME" ]; then
  BACKEND_URL="https://${CODESPACE_NAME}-5000.app.github.dev"
  FRONTEND_URL_VAL="https://${CODESPACE_NAME}-3000.app.github.dev"
  echo "      Codespace: $CODESPACE_NAME"
else
  BACKEND_URL="http://localhost:5000"
  FRONTEND_URL_VAL="http://localhost:3000"
  echo "      Local mode"
fi
echo "      Backend:   $BACKEND_URL"
echo "      Frontend:  $FRONTEND_URL_VAL"

# ── 3. Write backend .env ─────────────────────────────────────────────────────
echo "[3/6] Writing backend .env…"
cat > "$BACKEND/.env" << ENV
# Auto-generated by start.sh
DATABASE_URL="postgresql://helpdesk:helpdesk_dev@localhost:5432/it_ticketing?schema=public"

JWT_SECRET="itticket-jwt-$(hostname)-secret"
JWT_EXPIRES_IN="24h"
JWT_REFRESH_SECRET="itticket-refresh-$(hostname)-secret"
JWT_REFRESH_EXPIRES_IN="7d"

PORT=5000
NODE_ENV=development
FRONTEND_URL=$FRONTEND_URL_VAL

SMTP_HOST=
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=
SMTP_PASS=
EMAIL_FROM="IT Helpdesk <helpdesk@helpdesk.local>"

LOG_LEVEL=info
ENV

# ── 4. Write frontend .env ────────────────────────────────────────────────────
echo "[4/6] Writing frontend .env…"
echo "REACT_APP_API_URL=$BACKEND_URL/api" > "$FRONTEND/.env"

# ── 5. Start Postgres ─────────────────────────────────────────────────────────
echo "[5/6] Starting Postgres…"
cd "$ROOT"

# Find container name dynamically
CONTAINER_NAME=$(docker compose ps -q db 2>/dev/null | head -1)
if [ -z "$CONTAINER_NAME" ]; then
  docker compose up -d db
fi

echo "      Waiting for Postgres…"
for i in $(seq 1 30); do
  if docker compose exec -T db pg_isready -U helpdesk -d it_ticketing -q 2>/dev/null; then
    echo "      Postgres ready ✓"
    break
  fi
  sleep 2
  if [ $i -eq 30 ]; then
    echo "ERROR: Postgres did not become ready. Check: docker ps"
    exit 1
  fi
done

# ── 6. DB push + seed ─────────────────────────────────────────────────────────
echo "[6/6] Syncing schema and seeding…"
cd "$BACKEND"
npm install --silent 2>/dev/null
npx prisma db push --skip-generate 2>/dev/null || npx prisma db push
npx prisma generate --silent 2>/dev/null || true
node prisma/seed.js

# ── Start backend ─────────────────────────────────────────────────────────────
echo ""
echo "▶  Starting backend (port 5000)…"
npm run dev &
BACKEND_PID=$!
sleep 3

# ── Start frontend ────────────────────────────────────────────────────────────
echo "▶  Starting frontend (port 3000)…"
cd "$FRONTEND"
npm install --silent 2>/dev/null
npm start &
FRONTEND_PID=$!

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Services are starting.                                      ║"
echo "║                                                              ║"
echo "║  Backend:  $BACKEND_URL/health"
echo "║  Frontend: $FRONTEND_URL_VAL"
echo "║                                                              ║"
echo "║  Login:  admin@helpdesk.local  /  Admin@12345                ║"
echo "║                                                              ║"
echo "║  ⚠ ACTION REQUIRED — Ports tab:                             ║"
echo "║    Right-click port 5000 → Port Visibility → Public          ║"
echo "║    Right-click port 3000 → Port Visibility → Public          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

wait $BACKEND_PID $FRONTEND_PID
